keep_joints:
  - x_taxel_1_f1_dg5f_ft_01_joint
  - x_taxel_1_f1_dg5f_ft_02_joint
  - x_taxel_1_f1_dg5f_ft_03_joint
  - x_taxel_1_f1_dg5f_ft_04_joint
  - x_taxel_1_f1_dg5f_ft_05_joint
  - x_taxel_1_f1_dg5f_ft_06_joint
  - x_taxel_1_f1_dg5f_ft_07_joint
  - x_taxel_1_f1_dg5f_ft_08_joint
  - x_taxel_1_f1_dg5f_ft_09_joint
  - x_taxel_1_f1_dg5f_ft_10_joint
  - x_taxel_1_f1_dg5f_ft_11_joint
  - x_taxel_1_f1_dg5f_ft_12_joint
  - x_taxel_1_f2_dg5f_ft_01_joint
  - x_taxel_1_f2_dg5f_ft_02_joint
  - x_taxel_1_f2_dg5f_ft_03_joint
  - x_taxel_1_f2_dg5f_ft_04_joint
  - x_taxel_1_f2_dg5f_ft_05_joint
  - x_taxel_1_f2_dg5f_ft_06_joint
  - x_taxel_1_f2_dg5f_ft_07_joint
  - x_taxel_1_f2_dg5f_ft_08_joint
  - x_taxel_1_f2_dg5f_ft_09_joint
  - x_taxel_1_f2_dg5f_ft_10_joint
  - x_taxel_1_f2_dg5f_ft_11_joint
  - x_taxel_1_f2_dg5f_ft_12_joint
  - x_taxel_1_f3_dg5f_ft_01_joint
  - x_taxel_1_f3_dg5f_ft_02_joint
  - x_taxel_1_f3_dg5f_ft_03_joint
  - x_taxel_1_f3_dg5f_ft_04_joint
  - x_taxel_1_f3_dg5f_ft_05_joint
  - x_taxel_1_f3_dg5f_ft_06_joint
  - x_taxel_1_f3_dg5f_ft_07_joint
  - x_taxel_1_f3_dg5f_ft_08_joint
  - x_taxel_1_f3_dg5f_ft_09_joint
  - x_taxel_1_f3_dg5f_ft_10_joint
  - x_taxel_1_f3_dg5f_ft_11_joint
  - x_taxel_1_f3_dg5f_ft_12_joint
  - x_taxel_1_f4_dg5f_ft_01_joint
  - x_taxel_1_f4_dg5f_ft_02_joint
  - x_taxel_1_f4_dg5f_ft_03_joint
  - x_taxel_1_f4_dg5f_ft_04_joint
  - x_taxel_1_f4_dg5f_ft_05_joint
  - x_taxel_1_f4_dg5f_ft_06_joint
  - x_taxel_1_f4_dg5f_ft_07_joint
  - x_taxel_1_f4_dg5f_ft_08_joint
  - x_taxel_1_f4_dg5f_ft_09_joint
  - x_taxel_1_f4_dg5f_ft_10_joint
  - x_taxel_1_f4_dg5f_ft_11_joint
  - x_taxel_1_f4_dg5f_ft_12_joint
  - x_taxel_1_f5_dg5f_ft_01_joint
  - x_taxel_1_f5_dg5f_ft_02_joint
  - x_taxel_1_f5_dg5f_ft_03_joint
  - x_taxel_1_f5_dg5f_ft_04_joint
  - x_taxel_1_f5_dg5f_ft_05_joint
  - x_taxel_1_f5_dg5f_ft_06_joint
  - x_taxel_1_f5_dg5f_ft_07_joint
  - x_taxel_1_f5_dg5f_ft_08_joint
  - x_taxel_1_f5_dg5f_ft_09_joint
  - x_taxel_1_f5_dg5f_ft_10_joint
  - x_taxel_1_f5_dg5f_ft_11_joint
  - x_taxel_1_f5_dg5f_ft_12_joint
  - x_taxel_1_f1_mid_uSPa22_01_joint
  - x_taxel_1_f1_mid_uSPa22_02_joint
  - x_taxel_1_f1_mid_uSPa22_03_joint
  - x_taxel_1_f1_mid_uSPa22_04_joint
  - x_taxel_1_f2_mid_uSPa22_01_joint
  - x_taxel_1_f2_mid_uSPa22_02_joint
  - x_taxel_1_f2_mid_uSPa22_03_joint
  - x_taxel_1_f2_mid_uSPa22_04_joint
  - x_taxel_1_f3_mid_uSPa22_01_joint
  - x_taxel_1_f3_mid_uSPa22_02_joint
  - x_taxel_1_f3_mid_uSPa22_03_joint
  - x_taxel_1_f3_mid_uSPa22_04_joint
  - x_taxel_1_f4_mid_uSPa22_01_joint
  - x_taxel_1_f4_mid_uSPa22_02_joint
  - x_taxel_1_f4_mid_uSPa22_03_joint
  - x_taxel_1_f4_mid_uSPa22_04_joint
  - x_taxel_1_f5_mid_uSPa22_01_joint
  - x_taxel_1_f5_mid_uSPa22_02_joint
  - x_taxel_1_f5_mid_uSPa22_03_joint
  - x_taxel_1_f5_mid_uSPa22_04_joint
  - x_taxel_1_f1_prox_uSPa22_01_joint
  - x_taxel_1_f1_prox_uSPa22_02_joint
  - x_taxel_1_f1_prox_uSPa22_03_joint
  - x_taxel_1_f1_prox_uSPa22_04_joint
  - x_taxel_1_f2_prox_uSPa22_01_joint
  - x_taxel_1_f2_prox_uSPa22_02_joint
  - x_taxel_1_f2_prox_uSPa22_03_joint
  - x_taxel_1_f2_prox_uSPa22_04_joint
  - x_taxel_1_f3_prox_uSPa22_01_joint
  - x_taxel_1_f3_prox_uSPa22_02_joint
  - x_taxel_1_f3_prox_uSPa22_03_joint
  - x_taxel_1_f3_prox_uSPa22_04_joint
  - x_taxel_1_f4_prox_uSPa22_01_joint
  - x_taxel_1_f4_prox_uSPa22_02_joint
  - x_taxel_1_f4_prox_uSPa22_03_joint
  - x_taxel_1_f4_prox_uSPa22_04_joint
  - x_taxel_1_f5_prox_uSPa22_01_joint
  - x_taxel_1_f5_prox_uSPa22_02_joint
  - x_taxel_1_f5_prox_uSPa22_03_joint
  - x_taxel_1_f5_prox_uSPa22_04_joint
  - x_taxel_1_palm_uSPa46_01_joint
  - x_taxel_1_palm_uSPa46_02_joint
  - x_taxel_1_palm_uSPa46_03_joint
  - x_taxel_1_palm_uSPa46_04_joint
  - x_taxel_1_palm_uSPa46_05_joint
  - x_taxel_1_palm_uSPa46_06_joint
  - x_taxel_1_palm_uSPa46_07_joint
  - x_taxel_1_palm_uSPa46_08_joint
  - x_taxel_1_palm_uSPa46_09_joint
  - x_taxel_1_palm_uSPa46_10_joint
  - x_taxel_1_palm_uSPa46_11_joint
  - x_taxel_1_palm_uSPa46_12_joint
  - x_taxel_1_palm_uSPa46_13_joint
  - x_taxel_1_palm_uSPa46_14_joint
  - x_taxel_1_palm_uSPa46_15_joint
  - x_taxel_1_palm_uSPa46_16_joint
  - x_taxel_1_palm_uSPa46_17_joint
  - x_taxel_1_palm_uSPa46_18_joint
  - x_taxel_1_palm_uSPa46_19_joint
  - x_taxel_1_palm_uSPa46_20_joint
  - x_taxel_1_palm_uSPa46_21_joint
  - x_taxel_1_palm_uSPa46_22_joint
  - x_taxel_1_palm_uSPa46_23_joint
  - x_taxel_1_palm_uSPa46_24_joint
